version: "3.7"

name: node-res-desiot

services:
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=Asia/Jakarta
    ports:
      - "1880:1880"
    networks:
      - node-red-net
    volumes:
      - node-red-desiot-data:/data
  
  emqx:
    image: emqx:latest
    environment:
    - "EMQX_NODE__NAME=emqx@node.emqx.io"
    - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
    networks:
      emqx-bridge:
        aliases:
        - node.emqx.io
    ports:
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083

volumes:
  node-red-desiot-data:

networks:
  node-red-net:
  emqx-bridge:
    driver: bridge
  